# fly.toml app configuration file generated for conecta-loja-postgres on 2025-11-12T22:43:24-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'conecta-loja-postgres'
primary_region = 'gru'

[build]
  image = 'flyio/postgres:17'

[env]
  POSTGRES_DB = "conecta_loja_backend"
  POSTGRES_USER = "postgres"
  POSTGRES_HOST_AUTH_METHOD = "trust"

[http_service]
  internal_port = 5432
  force_https = false  # PostgreSQL n√£o precisa de HTTPS
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
